# Escolha o tipo de dado mais adequado para cada uma das situações abaixo e caso julgue necessário, 
# explique o motivo da escolha.
        a) a população da terra = int()
        b) a temperatura média de ontem = float()
        c) o nome de uma novela brasileira = str()
        d) a potência de uma lâmpada = float()
        e) a população de um município = int()
        f) o peso de uma pessoa = float()
        g) a velocidade do vento na região de uma determinada usina eólica = float()
        h) a altura de uma pessoa em metros = float()
        i) a altura de uma pessoa em centímetros = int()
        j) a cotação do dólar em reais = float()
        k) pontuação de um time em um jogo de basquete = int()
        l) o preço de uma TV = float()
        m) o salário de um funcionário = float()
        n) o número de pernas de um animal = int()
        o) o preço de um automóvel = float()